version: "2.0"
services:
  dgraph-zero:
    image: unigraph-dgraph:latest
    networks:
      - unigraph-net
    volumes:
      - /opt/unigraph/data:/dgraph
    command: dgraph zero --my=dgraph-zero:5080
    ports:
      - 5080:5080
      - 6080:6080
    restart: unless-stopped

  dgraph-alpha:
    image: unigraph-dgraph:latest
    networks:
      - unigraph-net
    volumes:
      - /opt/unigraph/data:/dgraph
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080 --whitelist=172.26.0.0/29
    ports:
      - 8080:8080
      - 9080:9080
    restart: unless-stopped

  backend:
    image: unigraph-backend:latest
    networks:
      - unigraph-net
    volumes:
      - /etc/unigraph:/config
    ports:
      - 3001:3001
    depends_on:
      - "dgraph-alpha"
    command: /bin/bash -i /opt/unigraph/scripts/start_backend.sh -h dgraph-alpha 
    restart: unless-stopped

  explorer: 
    image: unigraph-explorer:latest
    networks:
      - unigraph-net
    ports:
      - 3000:3000
    depends_on:
      - "backend"
    restart: unless-stopped

networks:
  unigraph-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/29

